namespace Boytrix.UI.Common.Utilities.Enums
{
    public enum SecurityActions
    {
        Login,
        Logout,
        ChangePassword
    }

    public enum SecurityPermissionEnum
    {
        PURCHASE_ORDER,
        PURCHASE_ORDER_SEND_PREADVICE_3PL,
        PURCHASE_DROPSHIPPINGDESPATCH,
        PURCHASE_ORDER_MERGING,
        GOODS_RECEIVED_3PL_WAREHOUSE,
        CUSTOMER_RETURNS_3PL_WAREHOUSE,
        STOCK_ADJUSTMENTS_3PL_WAREHOUSE,
        INVOICE_MAPPING,
        GOODRECEIVED_MAPPING,
        GOODSRECEIVEDMERGE,
        IMPORT_PURCHASE_ORDER,
        PRODUCTS,
        PRODUCTS_SETTINGS,
        SUPPLIERS,
        WAREHOUSES,
        SHIPPINGMETHODS,
        PRODUCTS_IMPORT,
        PRODUCTS_EXPORT,
        PRODUCTSUPPLIER_UPDATE,
        IMPORT_PROMO_PRODUCTS,
        INVENTORY_STOCK_VIEW,
        INVENTORY_STOCK_SYNC_3PL,
        STOCK_ADJUSTMENTS,
        ORDERS,
        ORDERS_UPDATE_WAREHOUSE,
        ORDERS_CANCEL_OPTION,
        ORDERS_EXPORT_3PL_WAREHOUSE,
        ORDERS_STATUS_UPDATE_3PL,
        END_OF_DAY_PROCESS,
        MANAGE_USERS,
        MANAGE_GROUPS,
        MANAGE_PERMISSIONS,
        SYNC_PROD_SUP_INFO,
        UPDATE_OFBIZ_INVENTORY,

        REPORT_PRODUCT_PURCHASE_HISTORY,
        REPORT_SUPPLIER_PURCHASE_ANALYSIS,
        REPORT_STOCK_AJUSTMENT,
        REPORT_CATALOG_LINKPRODUCTS,
        REPORT_CATALOG_ALLPRODUCTS,
        REPORT_WH_ORDERDESPATCH,
        REPORT_WH_STOCKREMAINING,
        REPORT_ACTIVEJIT,
        REPORT_ACTIVEWAREHOUSESKU,
        REPORT_ORDER_OOS,
        REPORT_ORDER_COMPLETEDORDERS,
        REPORT_ORDER_DESPATCHORDERS,
        REPORT_PRODUCTSUPPLIERDETAIL,
        REPORT_SUPPLIER_PRICECHANGEHISTORY,

        SUPPLIERINVOICEEXPORT,
        DEV_TESTFORM,
        REPORT_SUPPLIERINVOICEEXPORT,
        REPORT_CANCELLEDORDERS,
        REPORT_SUPPLIER_PURCHASE_BY_WAREHOUSE_REPORT,
        REPORT_STOCK_VALUATION_REPORT,
        ORDERS_LINEITEM_CAN_CANCEL_OPTION,

        SYSTEM_CRONJOBS,
        SYSTEM_SCHEDULE_MANAGEMENT
    }

}
